# Generated by Django 3.1.3 on 2022-09-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest_type',
            old_name='name',
            new_name='contest_type',
        ),
    ]
