# Generated by Django 3.1.3 on 2022-08-16 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20220813_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=400)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.userpost')),
            ],
        ),
    ]
