# Generated by Django 3.1.3 on 2022-08-16 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_reportpost_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportPostReason', to='post.report'),
        ),
    ]
