# Generated by Django 3.1.3 on 2022-08-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20220816_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='post_id',
            field=models.CharField(max_length=100),
        ),
    ]
