# Generated by Django 3.1.3 on 2022-09-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0007_identitydocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='verificationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkType', models.CharField(max_length=250)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
