# Generated by Django 3.1.3 on 2022-09-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0008_verificationlinks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='identityDocuments',
            new_name='identityDocument',
        ),
        migrations.RenameModel(
            old_name='verificationLinks',
            new_name='verificationLink',
        ),
    ]
