# Generated by Django 3.1.3 on 2022-09-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0009_auto_20220905_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='userVerificationDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('docPath', models.FileField(default=None, null=True, upload_to='identityDocuments')),
                ('userVerificationLinkId', models.IntegerField()),
                ('identityDocument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zipchoAdmin.identitydocument')),
            ],
        ),
        migrations.CreateModel(
            name='userVerificationLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstLink', models.IntegerField(null=True)),
                ('firstLinkPath', models.CharField(max_length=400, null=True)),
                ('secondLink', models.IntegerField(null=True)),
                ('secondLinkPath', models.CharField(max_length=400, null=True)),
                ('thirdLink', models.IntegerField(null=True)),
                ('thirdLinkPath', models.CharField(max_length=400, null=True)),
                ('fourthLink', models.IntegerField(null=True)),
                ('fourthLinkPath', models.CharField(max_length=400, null=True)),
                ('fifthLink', models.IntegerField(null=True)),
                ('fifthLinkPath', models.CharField(max_length=400, null=True)),
                ('userVerificationDocs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zipchoAdmin.userverificationdocs')),
            ],
        ),
    ]
