# Generated by Django 3.1.3 on 2022-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0010_userverificationdocs_userverificationlinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationlinks',
            name='userVerificationDocs',
            field=models.IntegerField(null=True),
        ),
    ]
