# Generated by Django 3.1.3 on 2022-09-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zipchoAdmin', '0011_auto_20220905_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationdocs',
            name='userVerificationLinkId',
            field=models.IntegerField(null=True),
        ),
    ]
