# Generated by Django 3.1.3 on 2022-08-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20220813_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
