# Generated by Django 3.1.3 on 2022-08-18 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_notificationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='interactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.BooleanField(default=True)),
                ('comments', models.BooleanField(default=True)),
                ('mentions', models.BooleanField(default=True)),
                ('messages', models.BooleanField(default=True)),
                ('activityStatus', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interactions',
            },
        ),
    ]
