# Generated by Django 3.1.3 on 2022-09-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_user_isonboardingcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isZipchoVerified',
            field=models.BooleanField(default=False),
        ),
    ]
