# Generated by Django 3.1.3 on 2022-09-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_user_iszipchoverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isZipchoVerified',
            field=models.IntegerField(default=0),
        ),
    ]
