name : CI/CD Pipeline for Zipcho Development
on:
  push :
    branches: [ develop ]
jobs : 
    Continuous-Integration : 
      runs-on: ubuntu-latest
      steps : 
        # Step 1 : 
          - uses: actions/checkout@v2
        # Step 2 : 
          - name: Set up Python 3.9
            uses : actions/setup-python@v2
            with:
              python-version: 3.9 
        # Step 3 : 
          - name : Install Depedenices
            run : pip install -r requirements.txt
        # Step 4 : 
          - name : Configure AWS Credentials
            uses : aws-actions/configure-aws-credentials@v1
            with : 
              aws-access-key-id : ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ap-south-1
        # Step 5 :
          # -name : build Zipcho Chat App
          # run : python manage.py
    Continuous-Deployment : 
      runs-on: ubuntu-latest
      needs: [Continuous-Integration]
      if: github.ref == 'refs/heads/develop'
      steps:

        # Step 1
        - name : Configure Aws Credentials
          uses :  aws-actions/configure-aws-credentials@v1
          with: 
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
            aws-region: ap-south-1
        # Step 2  
        - name : Create CodeDeploy Deployment 
          id : deploy
          run : | 
            aws deploy create-deployment \
            --application-name 	zipchoDevelopmentCodeDeploy \
            --deployment-group-name zipchoDevelopmentDeploymentGroup \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
