# Generated by Django 3.1.3 on 2022-08-13 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificationService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='fromId',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='authentication.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifications',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
