# Generated by Django 3.1.3 on 2022-08-24 04:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notificationService', '0002_auto_20220813_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='lastVisitedTime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 24, 4, 2, 12, 4699, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
